Homework #1 Task #1. Касацкий Всеслав Игоревич
VseslavKasatsky/spbu_kotlin_course pull request #1
Opened 2021-02-26 20:54 UTC by VseslavKasatsky

2021-02-28 18:36 UTC, VseslavKasatsky commented
@nbirillo инвайт в репозиторий примите пожожда

2021-03-01 10:06 UTC, nbirillo requested changes

2021-03-01 10:06 UTC, nbirillo commented on src/main/kotlin/firsthomework/task_1.kt
> +    var input: Int = readLine()!!.toInt()
Не используй `!!`, используй `?.` и элвис оператор (это было на паре)

2021-03-01 10:06 UTC, nbirillo commented on src/main/kotlin/firsthomework/task_1.kt
> +        print("Please enter a number greater than 0: ")
greater or equal :)

2021-03-01 10:06 UTC, nbirillo commented on src/main/kotlin/firsthomework/task_1.kt
> +    var input: Int = readLine()!!.toInt()
А еще я могу ввести строку например и `toInt` упадет)

2021-03-01 12:39 UTC, nbirillo approved these changes
Зачтено

2021-03-01 12:39 UTC, merged