Homework#3 Task#2 Касацкий.В
VseslavKasatsky/spbu_kotlin_course pull request #12
Opened 2021-03-19 14:11 UTC by VseslavKasatsky

2021-03-19 14:35 UTC, VseslavKasatsky commented
В 4.1 будет изменена немного архитектура, поэтому тесты немного придется переделать (Это к тому, что небольшие костыльки будут убраны)

2021-03-22 21:13 UTC, cupertank requested changes

2021-03-22 21:13 UTC, cupertank commented on build.gradle.kts
> +    implementation("org.junit.jupiter:junit-jupiter:5.4.2")
Это должно быть testImplementation

2021-03-22 21:13 UTC, cupertank commented on build.gradle.kts
> +    implementation("org.junit.jupiter:junit-jupiter:5.4.2")
ну и версии сопоставь...

2021-03-22 21:13 UTC, cupertank commented on src/test/kotlin/action/ActionsTest.kt
> +internal class InsertAtStartEndTest {
AtStartEnd???)))

2021-03-22 21:13 UTC, cupertank commented on src/test/kotlin/action/CommandStorageTest.kt
> +        assertEquals("[]", File("temp.json").readText())
Больше одного assert'а в тестах это плохо. Сделай отдельно на пустой.

2021-03-22 21:13 UTC, cupertank commented on src/test/kotlin/action/CommandStorageTest.kt
> +        File("temp.json").delete()
Записывать и удалять файл в корне проекта некруто, почитай про TempDir в JUnit.

2021-03-23 19:51 UTC, cupertank requested changes

2021-03-23 19:51 UTC, cupertank commented on src/test/kotlin/action/ActionsTest.kt
> +internal class MoveTest {
Забыл добавить (но так как ты и так и так не укладываешься в дедлайн), то добавь тесты с некорректными границами мува при помощи assertThrows

2021-03-23 19:51 UTC, cupertank commented on src/test/kotlin/action/CommandStorageTest.kt
> +internal class CommandStorageTest {
Добавь комплексный тест со всеми экшенами для CommandStorage и undo и просто проверь его

2021-03-28 23:50 UTC, samorojy commented
@cupertank А когда уже ревью будет?((

2021-03-30 21:35 UTC, cupertank approved these changes

2021-03-30 21:40 UTC, merged