Homework#3 Task3 Касацкий.В
VseslavKasatsky/spbu_kotlin_course pull request #13
Opened 2021-03-22 10:13 UTC by VseslavKasatsky

2021-03-23 19:26 UTC, cupertank requested changes

2021-03-23 19:26 UTC, cupertank commented on build.gradle.kts
> +    implementation("junit:junit:3.8.2")
это who?

2021-03-23 19:26 UTC, cupertank commented on src/main/kotlin/homework1/task_3.kt
> +    val fileName = "src/main/resources/homework1/ActionList.json"
напоминаю что к ресурсам обращаются не так)
Прочитай как обращаться к ресурсам в Kotlin/Java

2021-03-23 19:26 UTC, cupertank commented on src/main/kotlin/homework1/task_3.kt
> +    val fileName = "src/main/resources/homework1/ActionList.json"
Почему это ваще сюда попало...

2021-03-23 19:26 UTC, cupertank commented on src/main/kotlin/homework3/YamlDeserialization.kt
> +fun getConfigFromYaml(yamlText: String) = Yaml.default.decodeFromString(Config.serializer(), yamlText)
Сделай эту функцию companion object у Config

2021-03-23 19:26 UTC, cupertank commented on src/main/kotlin/homework3/TestGenerator.kt
> +fun generateTest(inputFilePath: String, outputFilePath: String) {
Унеси эту функцию в companion object у TestGenerator, только назови её просто generate

2021-03-23 19:26 UTC, cupertank commented on src/main/kotlin/homework3/demoTask.kt
> +    val inputFileName = "src/main/resources/homework3/Config.Yaml"
Гуглим гуглим как работать с ресурсами в Kotlin/Java

2021-03-23 19:26 UTC, cupertank commented on src/test/kotlin/homework3/TestGeneratorTest.kt
> +                TestGeneratorTest::class.java.getResource("GeneratorTest1.kt").readText().replace("\r\n", "\n"),
А вот тут у тебя уже получается с ресурсами работать

2021-03-23 19:26 UTC, cupertank commented on src/test/kotlin/homework3/TestGeneratorTest.kt
> +    fun getKotlinFile(expected: String, input: Config) {
Я бы хотел, чтобы ты чтение expected проводил внутри теста, в аргументах у тебя получается дублирование кода просто

2021-03-23 19:26 UTC, cupertank commented on src/test/kotlin/homework3/YamlDeserializationTest.kt
> +                ), YamlDeserializationTest::class.java.getResource("ConfigTest1.yaml").readText()
аналогичное замечание как прошлое

2021-03-23 19:27 UTC, cupertank commented on build.gradle.kts
> +    implementation("junit:junit:3.8.2")
Я про 24 если что

2021-03-23 19:34 UTC, samorojy commented on build.gradle.kts
> +    implementation("junit:junit:3.8.2")
Это уже ничего. А вообще в KotlinPoet это предлагалось для .addAnnotation(Test::class), но он использует не совсем то, что нам нужно

2021-03-23 19:35 UTC, samorojy commented on src/main/kotlin/homework1/task_3.kt
> +    val fileName = "src/main/resources/homework1/ActionList.json"
Я просто папку добавил в ресурсах (Чтобы ресурсы каждой домашки лежали в нужной папке) 
Это для записи была штука, а не для чтения

2021-03-29 15:16 UTC, cupertank requested changes
Сделай ещё один тип параметризованных тестов, где аргументы у тебя будут просто папки в ресурсах. В каждой этой папке у тебя должен быть expected.kt и config.yaml. Читай их в тесте, генерируй по конфигу actual.kt куда-нибудь во временную папку и сравнивай.

2021-03-29 15:16 UTC, cupertank commented on src/test/kotlin/homework3/TestGeneratorTest.kt
> +                TestGeneratorTest::class.java.getResource("GeneratorTest1.kt").file,
Оставь в аргументах только названия файлов, чтение делай в самом тесте, у тебя получается много дубликатов кода

2021-03-29 15:16 UTC, cupertank commented on src/test/kotlin/homework3/YamlDeserializationTest.kt
> +                ), YamlDeserializationTest::class.java.getResource("ConfigTest1.yaml").file
аналогично унеси чтение в сам тест

2021-03-30 21:12 UTC, cupertank approved these changes

2021-03-30 21:12 UTC, cupertank commented
Резолви конфликты

2021-03-30 21:32 UTC, merged