Homework#4 Task2 Касацкий.В
VseslavKasatsky/spbu_kotlin_course pull request #15
Opened 2021-04-01 12:55 UTC by samorojy

2021-04-07 11:19 UTC, cupertank requested changes
В общем говоря, мне абсолютно не нравятся функции добавления и удаления, просто почитай алгоритмы на википедии и реализуй их, они там хорошо описаны

2021-04-07 11:19 UTC, cupertank commented on src/main/kotlin/homework4/AvlNode.kt
> +        return this.rightRotate()
кажется здесь ошибка))

2021-04-07 11:19 UTC, cupertank commented on src/main/kotlin/homework4/AvlNode.kt
> +    private fun leftRightRotate(): AvlNode<K, V> {
Назови bigLeftRotate....
Просто это известное понятие для AVL деревьев, почему бы и нет...

2021-04-07 11:19 UTC, cupertank commented on src/main/kotlin/homework4/AvlNode.kt
> +    private fun rightLeftRotate(): AvlNode<K, V> {
bigRightRotate

2021-04-07 11:19 UTC, cupertank commented on src/main/kotlin/homework4/AvlNode.kt
> +            else -> false
мне кажется, что key == this.key можно вставить вместо такого else

2021-04-07 11:19 UTC, cupertank commented on src/main/kotlin/homework4/AvlTree.kt
> +        }
Насколько мне известно, мы должны в рекурсии снизу вверх обновлять высоты и балансировать дерево, а не так как у тебя, это важно

2021-04-07 11:19 UTC, cupertank commented on src/main/kotlin/homework4/AvlNode.kt
> +                    leftNode?.add(key, newValue) ?: false
Где-то здесь мы должны обновлять высоты и балансировать)

2021-04-07 11:19 UTC, cupertank commented on src/main/kotlin/homework4/AvlNode.kt
> +class AvlNode<K : Comparable<K>, V>(override var key: K, override var value: V) : Map.Entry<K, V> {
Стой стой стой, мне кажется, ключ точно должен быть val, а value точно должно быть private var, ниже должен быть оверрайд с геттером, чтобы изменять значение можно было только внутри реализации

2021-04-07 11:19 UTC, cupertank commented on src/main/kotlin/homework4/AvlNode.kt
> +    private fun removeByKey(key: K, previousNode: AvlNode<K, V>?): AvlNode<K, V>? {
Алгоритм удаления мне тоже не нравится...
Просто почитай википедию и сделай как там...

Я честно не понимаю вот этих leftNode == null и тд
К тому же при удалении минимальной вершины балансировка опять должна идти снизу вверх чего у тебя не происходит

2021-04-07 11:19 UTC, cupertank commented on src/main/kotlin/homework4/AvlNode.kt
> +    fun isContainsValue(value: V): Boolean {
мне кажется это можно через fun isContainsValue(value: V) = ... прописать

2021-04-07 11:19 UTC, cupertank commented on src/main/kotlin/homework4/AvlTree.kt
> +            return entries.toSet()
Тебе не нужно тут делать toSet, MutableSet наследует Set поэтому ты можешь возвращать просто entries и произойдет обычное понижение типа. Любая Mutable структура в котлине наследуется от немутабельной версии

2021-04-07 11:19 UTC, cupertank commented on src/main/kotlin/homework4/AvlTree.kt
> +            return entries.map { it.value }.toSet()
Функция map возвращает List<V>, который в свою очередь является Collection<V>, зачем toSet?

2021-04-07 11:21 UTC, cupertank commented
Как вишенку добавлю тебе падающий тест, потом сделай приватным balanceFactor либо придумай как его нормально вытащить наружу, им можно хорошо потестировать всё дерево)))

2021-04-19 23:59 UTC, cupertank requested changes

2021-04-19 23:59 UTC, cupertank commented on src/main/kotlin/homework4/AvlNode.kt
> +        }
Зачем так громоздко, сделай через get() = privateValue

2021-04-19 23:59 UTC, cupertank commented on src/test/kotlin/homework4/AvlTreeTest.kt
> +import kotlin.math.abs
Мне кажется что здесь есть какие-то левые импорты

2021-04-19 23:59 UTC, cupertank commented on src/main/kotlin/homework4/AvlNode.kt
> +        }
А зачем тут проверки на нулл? Просто то, что у тебя под ифами как раз это и делает: если нулл, то ничего не сделает, если не нулл, то сделает

2021-04-19 23:59 UTC, cupertank commented on src/main/kotlin/homework4/AvlTree.kt
> +        }
аналогично через равно

2021-04-19 23:59 UTC, cupertank commented on src/main/kotlin/homework4/AvlTree.kt
> +        }
равно

2021-04-19 23:59 UTC, cupertank commented on src/main/kotlin/homework4/AvlTree.kt
> +            if (root?.add(key, value) == true) {
У тебя add дает bool и ты сравниваешь bool и bool чтобы получить ещё один bool

2021-04-19 23:59 UTC, cupertank commented on src/test/kotlin/homework4/AvlTreeTest.kt
> +        assertEquals(setOf(0, true), setOf(tree.size, tree.isEmpty()))
Проверять какие-то сеты это полная дичь. Тут можно просто проверить isEmpty

2021-04-19 23:59 UTC, cupertank commented on src/test/kotlin/homework4/AvlTreeTest.kt
> +        assertEquals(setOf(true, false), setOf(tree.containsValue("First"), tree.containsValue("Third")))
Сделай два ассерта. Проблема нескольких ассертов у вас раньше была в том, что вы проверяли несколько функций одновременно, когда ты двумя ассертами проверяешь один функционал просто несколько раз, то это окей. Не надо городить сеты

2021-05-15 12:35 UTC, samorojy commented
@cupertank Merge как бы хочется уже :)

2021-05-16 16:27 UTC, cupertank approved these changes

2021-05-16 16:27 UTC, merged