Homework#4 Task#1 Касацкий.В
VseslavKasatsky/spbu_kotlin_course pull request #16
Opened 2021-04-02 19:09 UTC by samorojy

Можно спойлер-подсказку-совет-что-нибудь как пофиксить сериализацию?

2021-04-03 14:40 UTC, samorojy commented
P.S. Как-нибудь без костылей .-.

2021-04-06 20:20 UTC, cupertank requested changes
По поводу как это сделать.
Попытайся сначала перевести только экшены на дженерики, а в CommandStorage просто использовать экшены для интов и сериализацию только для интов. Тут тебе помогут: https://github.com/Kotlin/kotlinx.serialization/issues/1252.
Тебе скорее всего придется переделать твои тесты на запись и чтение.

Потом попытайся обобщить CommandStorage, но помни, что для всего дженерика сделать сериализиацию у тебя не получится и вынести сериализацию для <Int> отдельно

2021-04-06 20:20 UTC, cupertank commented on src/main/kotlin/action/Actions.kt
> +    abstract fun undoAction(numberList: MutableList<K>, storage: CommandStorage<K>)
Зачем ты сюда листы добавил?
Мне кажется тогда уж лучше оставить экшены на листах и просто нормально обрабатывать в CommandStorage в doAction

2021-04-06 20:34 UTC, samorojy commented on src/main/kotlin/action/Actions.kt
> +    abstract fun undoAction(numberList: MutableList<K>, storage: CommandStorage<K>)
ответил в лс

2021-04-06 20:35 UTC, samorojy commented on src/main/kotlin/action/Actions.kt
> +    abstract fun undoAction(numberList: MutableList<K>, storage: CommandStorage<K>)
А хотелось бы видеть задания без костылей на костылях 🥺

2021-04-09 18:36 UTC, samorojy commented
![image](https://user-images.githubusercontent.com/71323710/114225951-9ed94b80-997b-11eb-9169-b9f32ea429cf.png)
А настоящие программисты правда разбираются в этом или просто копипастят? )

2021-04-09 18:56 UTC, cupertank reviewed
> ![image](https://user-images.githubusercontent.com/71323710/114225951-9ed94b80-997b-11eb-9169-b9f32ea429cf.png)
> А настоящие программисты правда разбираются в этом или просто копипастят? )

Разбираются))
У меня ушло две минуты чтобы понять

2021-04-09 18:56 UTC, cupertank commented on src/main/kotlin/action/Actions.kt
> +    abstract fun undoAction(numberList: MutableList<K>, storage: CommandStorage<K>)
Это не костыли на костылях, это вполне реальный случай как работать с сериализацией и дженериками

2021-04-09 19:18 UTC, cupertank requested changes

2021-04-09 19:18 UTC, cupertank commented on src/main/kotlin/action/CommandStorage.kt
> +    var numberList = mutableListOf<T>()
Почему это public var? Это не безопасно, мне кажется это должно быть private val в первую очередь...
Сделай отдельно val с геттером и чтобы там был List<T>

2021-04-09 19:18 UTC, cupertank commented on src/main/kotlin/action/CommandStorage.kt
> +                }
Тебе не нужно это потому что у тебя sealed class, это нужно для интерфейса

2021-04-19 23:33 UTC, cupertank approved these changes

2021-04-19 23:34 UTC, merged