ClassWork Касацкий.В
VseslavKasatsky/spbu_kotlin_course pull request #19
Opened 2021-04-17 16:16 UTC by samorojy

2021-04-23 15:07 UTC, SpirinEgor approved these changes
![Screenshot 2021-04-23 at 18 07 07](https://user-images.githubusercontent.com/22539802/115891410-baa21e80-a45e-11eb-96d6-07b75d5988f6.png)
Что-то с кодировкой...

В остальном очень годно получилось. Продолжай работу в этой же ветке дальше

2021-04-23 15:07 UTC, SpirinEgor commented on src/main/kotlin/homework8/Controller.kt
> +object Controller : Controller() {
А почему object, а не класс?

У тебя тут очень много логики собрано. Помни про паттерн с пары. Всю логику лучше вынести отдельно в модель. С появлением ботов и мультиплеера этот класс будет только разрастаться

2021-04-23 15:07 UTC, SpirinEgor commented on src/main/kotlin/homework8/UserInterface.kt
> +@file:Suppress("NoWildcardImports", "WildcardImport")
Атата

2021-05-13 20:14 UTC, samorojy commented
В настройках есть небольшой экспериментальный пункт. Работает с условностью :)

2021-05-17 22:09 UTC, samorojy commented
UPD: с размером игровым печаль-тоска.
Но WebSocket тема классная. 
====
В решении допущены допущения по типу:
-хранить currentBot  надо потому, что есть алгоритмы, которые нуждаются в сохранении предыдущих шагов. 
-Platform... без этого работать не будет из-за многопоточности и tornadoFx, они не дружат :)

2021-05-24 11:16 UTC, SpirinEgor requested changes
![Screenshot 2021-05-24 at 13 58 08](https://user-images.githubusercontent.com/22539802/119337956-14814880-bc98-11eb-8479-207d72beeb7a.png)

Почему-то сначала сыграл в ничью, потом выиграл. Он мне написал прямо с историей. Не думаю, что это фича :) Еще немного по дизайну -- settings сделал классно, но добавь еще на экран информацию о текущем выбранном режиме. Чтобы было понятно, что за игра сейчас начнется.

Онлайн как-то работает. Но почему-то даже когда ход противника, то я могу потыкать на своем поле за него... 

По архитектуре -- тебе надо добавить дополнительную абстракцию модели, чтобы убрать из контроллера вакханалию методов. Все-таки контроллер отвечает только за взаимодействие, не более. Вот копипаста из другого ревью, оно и к тебе подходит.
1. Сделать абстрактный класс модели. Там будет какая-то общая логика и абстрактный метод move (ну или по-своему назови)
2. Несколько наследников такого класса. PlayWithYouselfModel -- move просто ставит по переданным координатам нужный символ (не забудь про Enum). PlayWithBotModel -- инициализируется сложностью, а метод move принимает координаты, ставит значок и сразу же делает ход бота. Для ботов ты уже придумал хорошую абстракцию.
3. Если будет сетевой режим, то это еще одна реализация модели. Только в ней после хода игрока ты начинаешь слушать сокет в ожидании хода другого игрока.
4. Теперь в контроллере, ты как и раньше опрашиваешь игрока, как он хочет играть. По вызову start, контроллер просто создает нужную модель с заданными параметрами.

2021-05-24 11:16 UTC, SpirinEgor commented on src/main/kotlin/homework8/bots/hard/BotHard.kt
> +    override val botName = "Hard Bot: Egor"
![image](https://user-images.githubusercontent.com/22539802/119338379-94a7ae00-bc98-11eb-96ac-84c044e82bb6.png)

2021-05-24 11:16 UTC, SpirinEgor commented on src/main/kotlin/homework8/bots/hard/BotHard.kt
> +    @Suppress("ReturnCount", "ComplexMethod")
А может без этого? Ты всегда можешь сделать
```
return when (decision.stringType) {
    ...
}
```
И внутри не будет лишних return

2021-05-24 11:16 UTC, SpirinEgor commented on src/main/kotlin/homework8/bots/hard/BotHard.kt
> +    @Suppress("ReturnCount", "ComplexMethod")
Мне даже кажется, что идея должна такое подсказать была

2021-05-24 11:16 UTC, SpirinEgor commented on src/main/kotlin/homework8/bots/hard/BotHard.kt
> +        return defenseList[0]
И тут можно аккуратно на when переписать

2021-05-24 11:16 UTC, SpirinEgor commented on src/main/kotlin/homework8/controller/Controller.kt
> +@Suppress("TooManyFunctions")
Не надо :(

2021-05-24 11:16 UTC, SpirinEgor commented on src/main/kotlin/homework8/controller/Controller.kt
> +        currentBot = when (gameMode) {
Вот тут есть архитектурная ошибка. Контроллер начинает отвечать за процесс игры. Теперь он знает, что есть какие-то боты. Это неверно, во-первых, потому что боты есть не всегда, а во-вторых, потому что класс разрастается на несколько ответственностей. Лучшее решение -- вынести ботов в модели. То есть модель игры самим с собой, есть модель для игры с ботом. Тогда контроллер дергает только какой-то метод move, а модель сама уже решает, ходить там боту или нет.

2021-05-24 11:16 UTC, SpirinEgor commented on src/main/kotlin/homework8/controller/Controller.kt
> +    }
Опять же, контроллер что-то про онлайн знает. Хотя он есть не всегда. Более того, его не всегда надо создавать. Поэтому это надо вынести в отдельную модель.

2021-05-24 11:16 UTC, SpirinEgor commented on src/main/kotlin/homework8/controller/Controller.kt
> +    }
По поводу ошибки -- по-хорошему, тут надо ловить только то, что бросает сериализация Json или отправка по сокету. Если будет какая-то другая ошибка, то это не место чтобы ловить.
А чтобы приложение не падало, надо сам запуск оборачивать во что-то подобное.

2021-05-24 11:16 UTC, SpirinEgor commented on src/main/kotlin/homework8/controller/Controller.kt
> +    private suspend fun DefaultClientWebSocketSession.getTurn(buttons: List<List<Button>>) {
Аналогично

2021-05-24 11:16 UTC, SpirinEgor commented on src/main/kotlin/homework8/controller/Controller.kt
> +                    TurnStage.WIN_0 -> "Nought player won"
Надо просто enum классу задать сообщение, тогда when вообще не будет.
```
enum class TurnStage(endMessage: String) {
    DRAW("Draw")
    WIN_X("Cross player won")
    ...
}
```

И в коде будет:  `center = label(winningStage.endMessage)`

2021-05-24 11:16 UTC, SpirinEgor commented on src/main/kotlin/homework8/controller/Controller.kt
> +                }
Стили лучше вообще отдельно вынести

2021-05-24 11:16 UTC, SpirinEgor commented on src/main/kotlin/homework8/controller/GameMode.kt
> +enum class GameMode {
Вот тут тоже лучше всего задать какой-то `presentableName`. Чтобы потом аккуратно отображать.

2021-05-24 11:16 UTC, SpirinEgor commented on src/main/kotlin/homework8/demonstration.kt
> +        launch<TicTacToe>()
Отступ лишний

2021-05-24 11:16 UTC, SpirinEgor commented on src/main/kotlin/homework8/server/Application.kt
> +@Suppress("unused")
А что unused?

2021-05-24 11:16 UTC, SpirinEgor commented on src/main/kotlin/homework8/view/UserInterface.kt
> +                        @Suppress("MagicNumber")
Сделай один общий на весь файл. В самое начало поставь.

2021-05-27 12:16 UTC, nbirillo requested changes

2021-05-27 12:16 UTC, nbirillo commented on src/main/kotlin/homework8/controller/Controller.kt
> +                client.webSocket(method = HttpMethod.Get, host = "127.0.0.1", port = 8080, path = "/play") {
Обычно эта информация берется из конфига

2021-05-27 12:16 UTC, nbirillo commented on src/main/kotlin/homework8/controller/Controller.kt
> +        }
У тебя эта часть полностью повторяется в методе ниже за исключением того, что именно ты шлешь. Может функцию сделаешь?

2021-05-27 12:16 UTC, nbirillo commented on src/main/kotlin/homework8/controller/Controller.kt
> +        if (turnResult == TurnStage.DRAW || turnResult == TurnStage.WIN_0 || turnResult == TurnStage.WIN_X) {
Вот такие длинные условия сложно читать и их лучше выносить в функции

2021-05-27 12:16 UTC, nbirillo commented on src/main/kotlin/homework8/controller/Controller.kt
> +        }
У тебя по сути одно и тоже происходит, только в одном месте надо оборачивать в Platform.runLater, в другом нет. Может ты это как-то можешь объединить?

2021-05-29 17:07 UTC, SpirinEgor requested changes
По-прежнему много архитектурных проблем. Эту штуку сложно расширять и поддерживать. Простой пример: захотел ты сделать клиент для андроида. В идеале ты реализуешь только отображение на экране, а логика по подключению к серверу и игре просто переиспользуется. Однако сейчас тебе придется тянуть торнадо на андроид, много логики туда зашито.

2021-05-29 17:07 UTC, SpirinEgor commented on src/main/kotlin/homework8/controller/Controller.kt
> +@Suppress("TooManyFunctions")
Все еще не надо :(

2021-05-29 17:07 UTC, SpirinEgor commented on src/main/kotlin/homework8/controller/Controller.kt
> +    fun makeTurn(turnPlace: TurnPlace, buttons: List<List<Button>>, turnAuthor: TurnAuthor = TurnAuthor.SERVER) {
Очень сложная функция, каскад ифов с постоянной проверкой режима игры...

2021-05-29 17:07 UTC, SpirinEgor commented on src/main/kotlin/homework8/controller/Controller.kt
> +    fun makeTurn(turnPlace: TurnPlace, buttons: List<List<Button>>, turnAuthor: TurnAuthor = TurnAuthor.SERVER) {
Это все часть модели, непонятно зачем это в контроллере, который отвечает за контент представления

2021-06-04 10:41 UTC, SpirinEgor approved these changes
Получилось хорошо, супер!

2021-06-04 12:31 UTC, nbirillo commented on src/main/kotlin/homework8/controller/Controller.kt
> +                client.webSocket(method = HttpMethod.Get, host = "127.0.0.1", port = 8080, path = "/play") {
ну или хотя бы из специального градл файла, который не пушится в гит) который пропертис или что-нибудь такое. но в целом и так сойдет)

2021-06-04 12:31 UTC, nbirillo approved these changes
Мне тоже нравится!

2021-06-04 12:39 UTC, merged