Homework#6 Касацкий.В
VseslavKasatsky/spbu_kotlin_course pull request #20
Opened 2021-04-18 00:38 UTC by samorojy

2021-04-18 01:04 UTC, samorojy commented
![image](https://user-images.githubusercontent.com/71323710/115130779-f66e5b80-9ffa-11eb-867b-edc16d13473e.png)

2021-04-20 05:26 UTC, elena-lyulina requested changes

2021-04-20 05:26 UTC, elena-lyulina commented on src/main/kotlin/homework6/DrawArraySizeDependenceGraph.kt
> +class DrawArraySizeDependenceGraph : JFrame() {
Название классов не должны начинаться с глаголов, это скорее про методы-функции, можно заменить на ArraySizeDependenceGraphDrawer

2021-04-20 05:26 UTC, elena-lyulina commented on src/main/kotlin/homework6/DrawArraySizeDependenceGraph.kt
> +        for (arraySize in 2..25000) {
давай размер массива будет параметром конструктора, так же как и количество потоков

2021-04-20 05:26 UTC, elena-lyulina commented on src/main/kotlin/homework6/DrawArraySizeDependenceGraph.kt
> +            }
создание и инициализация массива можно вынести в отдельную функцию, так же посмотри на Random()

2021-04-20 05:26 UTC, elena-lyulina commented on src/main/kotlin/homework6/DrawArraySizeDependenceGraph.kt
> +    }
init должен быть после объявления свойств, но до методов
https://kotlinlang.org/docs/coding-conventions.html#class-layout

2021-04-20 05:26 UTC, elena-lyulina commented on src/main/kotlin/homework6/DrawThreadsDependenceGraph.kt
> +import org.jfree.chart.ChartPanel
с импортами что-то не то, зачем тебе пустые строки между ними?

2021-04-20 05:26 UTC, elena-lyulina commented on src/main/kotlin/homework6/demostration.kt
> +package homework6
названия классов должны быть с большой буквы https://kotlinlang.org/docs/coding-conventions.html#source-file-names

2021-04-20 05:26 UTC, elena-lyulina commented on src/main/kotlin/homework6/mergeSort.kt
> +fun IntArray.merge(left: Int, middle: Int, right: Int) {
давай это тоже будет многопоточным

2021-04-20 05:26 UTC, elena-lyulina commented on src/main/kotlin/homework6/DrawArraySizeDependenceGraph.kt
> +class DrawArraySizeDependenceGraph : JFrame() {
более показательно будет иметь один график размера от времени, на котором будут несколько функций, соответствующих сортировкам с разным количеством потоков

2021-04-20 05:26 UTC, elena-lyulina commented on src/main/kotlin/homework6/demostration.kt
> +    }
не очень хорошо запускать многопоточные сортировки из [event dispatch thread](https://docs.oracle.com/javase/tutorial/uiswing/concurrency/dispatch.html), что ты и делаешь, вызывая EventQueue.invokeLater. Этот поток для обработки ui, поэтому если ты от него же ответвляешься с сложными вычислениями, то все зависает

2021-04-20 05:26 UTC, elena-lyulina commented on src/test/kotlin/homework6/MergeSortTest.kt
> +        }
не вызываем assert в цикле, так будет совсем непонятно, на каком именно разе все упало, вместо этого используй параметризованные тесты

2021-04-20 05:26 UTC, elena-lyulina commented on src/test/kotlin/homework6/MergeSortTest.kt
> +    }
давай добавим больше случаев, опять же используй параметризованные тесты

2021-04-20 05:26 UTC, elena-lyulina commented on src/test/kotlin/homework6/MergeSortTest.kt
> +    }
ну и тут тоже хочется больше случаев

2021-04-20 05:26 UTC, elena-lyulina commented on src/main/kotlin/homework6/mergeSort.kt
> +}
main thread это довольно определенное понятие, не надо путать людей и называть какие-то потоки main
более того, ты можешь не создавать этот поток, а просто запустить mergeSortingMultiThread(0, this.lastIndex + 1, numberOfThreads)

2021-04-20 22:31 UTC, samorojy commented
Ревью желательно после вопроса в телеграме (21.04 утром)

2021-04-22 21:09 UTC, samorojy commented
![2021-04-22_23-48-42](https://user-images.githubusercontent.com/71323710/115785348-005fd800-a3c8-11eb-9790-fa9792c68236.png)
![2021-04-22_23-47-15](https://user-images.githubusercontent.com/71323710/115785352-01910500-a3c8-11eb-966d-22888f50b08b.png)
![2021-04-22_22-49-10](https://user-images.githubusercontent.com/71323710/115785353-01910500-a3c8-11eb-8081-d25b66c4e2c6.png)
![2021-04-22_22-34-46](https://user-images.githubusercontent.com/71323710/115785356-02299b80-a3c8-11eb-8c4d-0ff2a1b1364f.png)
Разные запуски (thread.start // thread.run)
https://neerc.ifmo.ru/wiki/index.php?title=%D0%9C%D0%BD%D0%BE%D0%B3%D0%BE%D0%BF%D0%BE%D1%82%D0%BE%D1%87%D0%BD%D0%B0%D1%8F_%D1%81%D0%BE%D1%80%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0_%D1%81%D0%BB%D0%B8%D1%8F%D0%BD%D0%B8%D0%B5%D0%BC 
Подробнее об алгоритме =))))))

2021-05-02 16:23 UTC, elena-lyulina requested changes
Уже неплохо! На самом деле зря ты саркастично относишься к своим графикам, если их запустить на разумных параметрах, получатся разумные ответы. Например, хочется запускать их на больших массивах (а не на массивах в 1000 элементов), не на каждом массиве, а через какой-то шаг + для потоков с количеством в степень двойки (прикрепила соответствующий график). 

И тогда действительно видно, что быстрее всех на 4-8-16 потоках (у меня 8 ядерный ноут), на 2х потоках все еще медленнее работает, на большем количестве потоков -- тоже медленне, причем, чем больше потоков, тем больше времени тратится на их создание и переключение, тем медленнее они работают 

![image](https://user-images.githubusercontent.com/24303332/116820046-af947000-ab7b-11eb-91f3-ee6bd790b9fe.png)

2021-05-02 16:23 UTC, elena-lyulina commented on src/main/kotlin/homework6/demostration.kt
> +    val ChartDrawer = ArraySizeDependenceGraphDrawer(
переменные с большой буквы -- это уже перебор :)

2021-05-02 16:23 UTC, elena-lyulina commented on src/main/kotlin/homework6/demostration.kt
> -package homework6
все еще файл с маленькой буквы, ты зачем-то даже зарезолвил комментарий соответствующий

2021-05-02 16:23 UTC, elena-lyulina commented on src/main/kotlin/homework6/demostration.kt
> +    ChartDrawer.isVisible = true
лучше это делать внутри init блока, а не снаружи, ты от пользователя должен скрывать всю логику и делать для него запуск как можно более проще

2021-05-02 16:23 UTC, elena-lyulina commented on src/main/kotlin/homework6/ArraySizeDependenceGraphDrawer.kt
> +        return arrayToSort
это все можно сделать одной строчкой 
`        return IntArray(tempArraySize) { Random.nextInt(Int.MAX_VALUE) }
`

2021-05-02 16:23 UTC, elena-lyulina commented on src/main/kotlin/homework6/ArraySizeDependenceGraphDrawer.kt
> +        return arrayToSort
а еще название странное, какой массив, чем заполнить?
 getRandomArray лучше отражает, что происходит

2021-05-02 16:23 UTC, elena-lyulina commented on src/main/kotlin/homework6/ArraySizeDependenceGraphDrawer.kt
> +            for (tempArraySize in 2..arraySize) {
чтобы не взрывался ноут, можно считать не для всех-всех массивов от 2 до arraySize, а тоже с каким-то шагом, его например тоже можно сделать параметром, а можно, например, решить, что ты хочешь иметь n точек на графе, и идти с шагом arraySize/n

2021-05-02 16:23 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorter.kt
> +        rightBoundSecondMergingPart: Int,
давай вместо передачи четырех аргументов с длинным названием, заведем data class MergingPart c полями leftBound и RigthBound, будет более читаемо

2021-05-02 16:23 UTC, elena-lyulina commented on src/test/kotlin/homework6/MergeSorterTest.kt
> +    fun getKotlinFile(expectedArray: IntArray, actualArray: IntArray, threadsNumber: Int) {
странное название для теста

2021-05-02 16:23 UTC, elena-lyulina commented on src/test/kotlin/homework6/MergeSorterTest.kt
> +internal class MergeSorterTest {
добавь, пожалуйста, тесты для merge

2021-05-02 16:23 UTC, elena-lyulina commented on src/main/kotlin/homework6/ArraySizeDependenceGraphDrawer.kt
> +        for (threadsNumber in minThreadsNumber until maxThreadsNumber step stepThread) {
на самом деле удобнее будет смотреть, как все меняется, если идти не линейно, а по степеням двойки, например, как минимум потому, что часто количество ядер - это степень двойки, и поэтому можно будет смотреть, как на таком количество потоков ведет себя сортировка
так что можно сделать параметрами minPower и maxPower и смотреть на все степени двойки между ними

2021-05-02 23:44 UTC, samorojy commented
![image](https://user-images.githubusercontent.com/71323710/116831671-6b27c500-abb9-11eb-9522-a2116fc0bdf8.png)

2021-05-04 17:37 UTC, elena-lyulina commented on src/main/kotlin/homework6/ArraySizeDependenceGraphDrawer.kt
> +            for (tempArraySize in 2..(arraySize + 2) step arraySizeStep) {
а почему такие странный размер? что за (arraySize + 2)?

2021-05-04 17:37 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorter.kt
> +        rightBoundSecondMergingPart: Int,
в mergeSortingMultiThread тоже надо MergingPart передавать, а не две границы отдельно

2021-05-04 17:38 UTC, elena-lyulina requested changes
Совсем чуть-чуть

2021-05-04 18:54 UTC, elena-lyulina approved these changes
Ура :)

2021-05-04 18:54 UTC, merged