Homework#7 Task#1 Касацкий.В
VseslavKasatsky/spbu_kotlin_course pull request #21
Opened 2021-04-19 18:46 UTC by samorojy

2021-04-19 18:46 UTC, samorojy commented
После мерджа 6-ой уберу дублирующийся код здесь

2021-04-19 18:47 UTC, samorojy commented
![image](https://user-images.githubusercontent.com/71323710/115287286-c1781b00-a158-11eb-8550-0ae6409ee1a9.png)
Какие-то медленные эти ваши корутины))))))

2021-04-20 18:30 UTC, samorojy commented
Переделываю правки с 6

2021-04-20 22:39 UTC, samorojy commented
Из 6-ой домашки перенесу изменения и многопоточность в слиянии

2021-04-30 10:27 UTC, samorojy commented
За неделю ситуация с 6-ой не изменилась, поэтому нынешнюю 6-ую перевел на корутины

2021-05-02 23:56 UTC, samorojy commented
![Uploading image.png…]()

2021-05-02 23:56 UTC, samorojy commented
![image](https://user-images.githubusercontent.com/71323710/116831954-243acf00-abbb-11eb-8ace-86662d7813b4.png)

2021-05-27 10:44 UTC, elena-lyulina requested changes

2021-05-27 10:44 UTC, elena-lyulina commented on src/main/kotlin/homework7/first/ArraySizeDependenceCoroutineGraphDrawer.kt
> +class ArraySizeDependenceCoroutineGraphDrawer(
давай ты все же уберешь дублирующийся код?

2021-05-27 10:44 UTC, elena-lyulina commented on src/main/kotlin/homework7/first/MergeSorterCoroutine.kt
> +class MergeSorterCoroutine {
давай многопоточная и корутинная сортировка будут реализовывать один и тот же интерфейс, с которым уже будет работать рисовальщик графов
так же можно вынести все общие функции
![image](https://user-images.githubusercontent.com/24303332/119812572-f3fffb00-bef0-11eb-9bff-c2c520783f3a.png)

2021-05-27 10:44 UTC, elena-lyulina commented on src/main/kotlin/homework7/first/MergeSorterCoroutine.kt
> +        val numberOfLeftThreads = numberOfThreads / 2
хм, а если numberOfThreads уже меньше или равно 1, у тебя все равно будет это запускаться в разных корутинах?

2021-05-31 19:20 UTC, elena-lyulina requested changes

2021-05-31 19:20 UTC, elena-lyulina commented on src/main/kotlin/homework7/first/MergeSorter.kt
> +open class MergeSorter {
у тебя все еще очень много повторяющегося кода, который можно вынести в общий базовый класс, например почти все реализации sort и merge за исключением вызовов разных функций 
![image](https://user-images.githubusercontent.com/24303332/120232946-52b0d600-c25d-11eb-9e36-6740efb3a820.png)

2021-05-31 19:20 UTC, elena-lyulina commented on src/main/kotlin/homework7/first/MergeSorter.kt
> +open class MergeSorter {
что можно сделать:
1. вынести весь этот метод в общий базовый класс
2. в базовом классе сделать абстрактный метод, который будет вызываться в тех местах, где все же есть различия
3. наследуемые классы будут реализовывать эти абстрактные методы по-своему

2021-05-31 19:20 UTC, elena-lyulina commented on src/main/kotlin/homework7/first/MergeSorter.kt
> +open class MergeSorter {
соответственно метод sort тоже будет одинаковый в двух твоих реализациях, его можно тоже вынести в общий базовый класс и сделать его наследуемым от твоего интерфейса

2021-05-31 19:20 UTC, elena-lyulina commented on src/main/kotlin/homework7/first/MergeSorterCoroutine.kt
>          for (i in arrayToSort.indices) arrayToSort[i] = temporaryArray[i]
тут кстати можно вызывать https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/copy-into.html

2021-05-31 19:20 UTC, elena-lyulina commented on src/main/kotlin/homework6/ArraySizeDependenceGraphDrawer.kt
> +class ArraySizeDependenceGraphDrawer<T : SorterInterface>(
если ты передаешь sorter, то необязательно класс делать дженериком, ты можешь тогда указать просто в параметрах тип private val sorter: SorterInterface

2021-06-01 17:16 UTC, elena-lyulina requested changes
почти :)

2021-06-01 17:16 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorterThread.kt
> +class MergeSorterThread : MergeSorter() {
не хватает модификаторов доступа, сделай все, что можно, приватным или протектед (в других местах тоже)

2021-06-01 17:16 UTC, elena-lyulina commented on src/main/kotlin/homework7/first/MergeSorter.kt
> +    @Suppress("LongParameterList")
количество параметров, конечно, слишком большое для понимания того, что происходит
подумай, мб можно сделать несколько дата классов и передавать их, а внутри метода уже обращаться к его свойствам
то же самое про runParallelMergeSorting

2021-06-01 17:16 UTC, elena-lyulina commented on src/main/kotlin/homework7/first/MergeSorter.kt
> +    fun IntArray.mergeSortingMultiThread(
в этой функции на 55 строчке точно должно быть == 1? что если их меньше 1?

2021-06-01 21:47 UTC, samorojy commented
Мне уже плохо над этим кодом работать 😣

2021-06-03 11:11 UTC, elena-lyulina approved these changes
> Мне уже плохо над этим кодом работать 😣

и мне :)
не буду больше тебя мучить, approve

2021-06-03 11:11 UTC, merged