Homework#7 Task#2 Касацкий.В
VseslavKasatsky/spbu_kotlin_course pull request #23
Opened 2021-05-07 23:07 UTC by samorojy

2021-05-13 16:16 UTC, elena-lyulina requested changes

2021-05-13 16:16 UTC, elena-lyulina commented on src/main/kotlin/homework7/second/Matrix.kt
> +        return string
строки нельзя складывать в циклах, они неизменяемые, поэтому каждый раз создается новая строка, а это плохо для производительности
в общих случаях можно использовать StringBuilder, в этом же лучше вызвать два раза joinToString (у него есть параметр transform)

2021-05-13 16:16 UTC, elena-lyulina commented on src/main/kotlin/homework7/second/Matrix.kt
> +        return true
хммммм а как бы это написать одной строчкой

2021-05-13 16:16 UTC, elena-lyulina commented on src/test/kotlin/homework7/second/MatrixTest.kt
> +        fun getCorrectData(): List<Arguments> = listOf(
давай тут будет еще пример с матрицами побольше, чем 3 на 3, а то так не интересно

2021-05-13 16:16 UTC, elena-lyulina commented on src/main/kotlin/homework7/second/Matrix.kt
> +    @Suppress("ComplexCondition")
он тебе нельзя показывает complex condition, я вот с трудом могу понять, что ты там проверяешь, давай ты это как-то по-понятному перепишешь

2021-05-13 16:16 UTC, elena-lyulina commented on src/main/kotlin/homework7/second/Matrix.kt
> +    @Suppress("ComplexCondition")
и еще некоторые вещи надо проверять при создании Matrix в ините, например, что у тебя все внутренние массивы одного размера

2021-05-13 16:22 UTC, samorojy commented on src/main/kotlin/homework7/second/Matrix.kt
> +        return true
ОЙ

2021-05-27 10:35 UTC, elena-lyulina requested changes
почти :)

2021-05-27 10:35 UTC, elena-lyulina commented on src/main/kotlin/homework7/second/Matrix.kt
> +    private fun isMatrixSquare(matrixToCheck: Matrix) {
чуть логичнее сделать это просто методом без аргументов и вызывать типа matrix.isMatrixSquare(), а внутри метода просто использовать свойство matrix

2021-05-27 10:35 UTC, elena-lyulina commented on src/main/kotlin/homework7/second/Matrix.kt
> +        require(matrix[0].isNotEmpty() || other.matrix[0].isNotEmpty()) {
тут же `и` должно быть а не `или`?

2021-05-27 21:35 UTC, elena-lyulina requested changes

2021-05-27 21:35 UTC, elena-lyulina commented on src/main/kotlin/homework7/second/Matrix.kt
> +    private fun Matrix.isMatrixSquare() {
можно без расширения писать же, просто private fun isMatrixSquare, а внутри соответственно просто использовать свойство matrix

2021-05-31 19:22 UTC, elena-lyulina approved these changes

2021-05-31 19:22 UTC, merged