Homework #1. Task #3. Касацкий Всеслав Игоревич
VseslavKasatsky/spbu_kotlin_course pull request #3
Opened 2021-03-02 14:05 UTC by VseslavKasatsky

2021-03-02 16:08 UTC, nbirillo commented
У тебя CI падает. Сначала его почини, потом напиши)

2021-03-02 17:02 UTC, VseslavKasatsky commented
@nbirillo я не шарил до этого в ооп, поэтому могу предсказать, что сейчас это будет на много conversa'шинов :)

2021-03-02 17:50 UTC, VseslavKasatsky commented
@nbirillo пофиксил CI

2021-03-04 11:14 UTC, nbirillo requested changes

2021-03-04 11:14 UTC, nbirillo commented on src/main/kotlin/action/actions.kt
> +        storage.actionList.add(0, this)
У тебя это действие выполняется везде одинаково. Действительно ли хорошо давать тогда доступ к списку экшенов тут или же лучше сделать функцию, которая будет добавлять экшен и везде ее вызыввать?

2021-03-04 11:14 UTC, nbirillo commented on src/main/kotlin/action/actions.kt
> +        storage.numberList.removeAt(0)
Есть `removeFirst` функция

2021-03-04 11:14 UTC, nbirillo commented on src/main/kotlin/action/actions.kt
> +        storage.numberList.removeAt(storage.numberList.size - 1)
Есть `removeLast` функция

2021-03-04 11:14 UTC, nbirillo commented on src/main/kotlin/action/actions.kt
> +        if (startIndex > storage.numberList.size || endIndex > storage.numberList.size) {
А я могу еще отрицательный индекс прислать

2021-03-04 11:14 UTC, nbirillo commented on src/main/kotlin/action/actions.kt
> +        storage.actionList.add(0, this)
Ну кажется, что нужно сделать функцию, которая может сдвинуть элемент и просто в применении ее вызвать с индексами в одном порядке, а в отмене - в другом

2021-03-04 11:14 UTC, nbirillo commented on src/main/kotlin/action/CommandStorage.kt
> +            error("ERROR! Action list is empty. Nothing to undo")
В задании я просила просто печатать ошибку, а не завершать работу программы

2021-03-04 11:14 UTC, nbirillo commented on src/main/kotlin/action/CommandStorage.kt
> +        actionList.removeAt(0)
removeLast

2021-03-04 12:07 UTC, VseslavKasatsky commented on src/main/kotlin/action/actions.kt
> +        if (startIndex > storage.numberList.size || endIndex > storage.numberList.size) {
Насчет ошибки комментарий тоже касается? 
Ну т.е просто вывести ошибку, но не завершать работу?

2021-03-05 07:46 UTC, nbirillo requested changes

2021-03-05 07:46 UTC, nbirillo commented on src/main/kotlin/action/actions.kt
> +        if ((startIndex !in (0..storage.numberList.size)) || (endIndex !in 0..storage.numberList.size)) {
Индексы можно получить проще - `list.indices`

2021-03-05 07:46 UTC, nbirillo commented on src/main/kotlin/action/actions.kt
> +package action
Может назовешь файлик с заглавной буквы?

2021-03-05 07:46 UTC, nbirillo commented on src/main/kotlin/action/actions.kt
> +        storage.numberList.add(0, number)
Я имела в виду здесь вызвать функцию стораджа ниже еще, которая добавит это действие в сторадж. Сейчас максимально странно выглядит вызов в мейне: Ты вызываешь метод у стораджа, в который передаешь экшен, который инитися по этому же стораджу.......

2021-03-05 08:14 UTC, VseslavKasatsky commented on src/main/kotlin/action/actions.kt
> +        storage.numberList.add(0, number)
Согласен, так изящнее

2021-03-05 08:40 UTC, VseslavKasatsky commented on src/main/kotlin/action/actions.kt
> +        storage.numberList.add(0, number)
Надеюсь, я правильно понял

2021-03-05 15:15 UTC, nbirillo approved these changes
Зачтено

2021-03-05 15:15 UTC, merged