Homework#2 task#1 Касацкий Всеслав
VseslavKasatsky/spbu_kotlin_course pull request #5
Opened 2021-03-08 16:49 UTC by VseslavKasatsky

2021-03-09 15:06 UTC, nbirillo requested changes

2021-03-09 15:06 UTC, nbirillo commented on build.gradle.kts
> +    outputDirectory.set(file("src"))
Кажется, что не хочется это хранить в папке `src`. Лучше какая-то папка `docs` в корне или вообще в `build` + не надо это пушить в гит

2021-03-09 15:06 UTC, nbirillo commented on build.gradle.kts
> +    moduleName.set("CommandStorage")
Ну это сейчас там только сторадж, а потом и другие домашки будут)

2021-03-09 17:13 UTC, samorojy commented
Что-то такое подразумевалось?

2021-03-10 09:37 UTC, nbirillo approved these changes
Ага, теперь все хорошо, зачтено!

2021-03-10 09:37 UTC, merged