Homework#2 Task#2 Касацкий Всеслав
VseslavKasatsky/spbu_kotlin_course pull request #6
Opened 2021-03-08 20:06 UTC by VseslavKasatsky

2021-03-09 15:43 UTC, nbirillo requested changes

2021-03-09 15:43 UTC, nbirillo commented on src/main/kotlin/homework2/task_2.kt
> +    val array: IntArray = intArrayOf(NUMBER0, NUMBER1, NUMBER2, NUMBER3, NUMBER3, NUMBER2, NUMBER0, NUMBER1)
Ну давай уже с клавиатуры считывать хотя бы

2021-03-09 15:43 UTC, nbirillo commented on src/main/kotlin/homework2/task_2.kt
> +    return set.toIntArray().reversedArray()
Ну это выглядит как-то так себе. Помни, что for мы стараемся не использовать

2021-03-09 19:27 UTC, samorojy commented
@nbirillo А можете еще немного прояснить с IntArray и Array<Int>
Где и что желательно использовать?

2021-03-10 09:23 UTC, nbirillo commented
В Котлине (собственно как и в джаве) есть такая штука как `boxing`\`unboxing`. То есть у тебя есть простой тип `int`, который упакован в тип `Integer`. Если ты будешь использовать `Array`, то у тебя будет массив с `Integer`, а если `IntArray` - то массив с `int`. То есть при добавлении элемента в `Array` у тебя будет всегда вызываться обертка-упаковка (`Integer.valueOf()`), а с `IntArray` - там примитивный тип `int` будет.  Интуитивно понятно (если нет, то спроси), так как требуется постоянно упаковка и распаковка, то это накладывает некие дополнительные временные расходы при выполнении программы. А еще `IntArray` можно не инициализировать полностью, а просто передать размер и тогда все остальное будет проинициализировано значением по умолчанию (в данном случае нулем).  Если же ты будешь создавать `Array`, то там еще можно передать функцию, которая будет возвращать значение по умолчанию, которым надо заполнить массив. Надеюсь так стало понятнее

2021-03-10 09:24 UTC, nbirillo commented
Ну собственно, если ты можешь использовать `IntArray`, то лучше используй его)
P.s.: если еще остались вопросы, напиши в тг, пожалуйста

2021-03-10 09:27 UTC, nbirillo approved these changes
Зачтено

2021-03-10 09:27 UTC, merged