Homework#2 task#3, Касацкий Всеслав
VseslavKasatsky/spbu_kotlin_course pull request #7
Opened 2021-03-11 16:08 UTC by VseslavKasatsky

2021-03-12 09:21 UTC, nbirillo requested changes

2021-03-12 09:21 UTC, nbirillo commented on src/main/kotlin/action/CommandStorage.kt
> +    fun pushSerializationToFile(name: String) {
Давай назовем как-то более читаемо) типа просто SerializeToFile например

2021-03-12 09:21 UTC, nbirillo commented on src/main/kotlin/action/CommandStorage.kt
> +    fun getSerializationFromFile(name: String) {
Тут тоже самое, можно использовать например deserialize

2021-03-12 09:21 UTC, nbirillo commented on src/main/kotlin/homework1/task_3.kt
> +    storage.getSerializationFromFile("src/main/kotlin/action/ActionList.json")
Давай ты в ресурсы положишь эти файлы?) ну или будешь относительные пути использовать тогда, где будет просто имя файла, но точно не так. А еще его можно поместить в переменную-константу

2021-03-12 09:21 UTC, nbirillo commented on src/main/kotlin/action/CommandStorage.kt
> +        file.write(Json.encodeToString(actionList))
Кажется немного не интуитивно, что у тебя actions сохраняются в обратном порядке. То есть, если убрать отмену действий, у тебя сохранится вот такой список:
```
[{"type":"action.Move","startIndex":0,"endIndex":3},{"type":"action.InsertAtEnd","number":5},{"type":"action.InsertAtStart","number":4},{"type":"action.InsertAtStart","number":3},{"type":"action.InsertAtStart","number":2},{"type":"action.InsertAtStart","number":1}]
```
Но кажется, что должно быть в обратном порядке :) Посмотри еще в сторону SerialName, чтобы сохранять не с такими автоматическими именами, а чтобы например там не было приписки action

2021-03-18 09:59 UTC, elena-lyulina requested changes

2021-03-18 09:59 UTC, elena-lyulina commented on src/main/kotlin/action/CommandStorage.kt
> +        val file = FileWriter(name)
FileWriter надо обязательно закрывать в конце, а не только делать flush, так что гугли внимательнее :)
а вообще лучше переделать на более лаконичное File(name).writeText(), там еще и не надо проверять, существует файл или нет -- если нет, он сам создастся

2021-03-18 09:59 UTC, elena-lyulina commented on src/main/kotlin/action/CommandStorage.kt
> +        val inputStream: InputStream = File(name).inputStream()
Тут примерно то же, что с FileWriter. Ты конечно используешь use, который выходя из блока закрывает bufferReader, но не уверена, что ты это делаешь осознанно. Давай использовать File(name).readText()

2021-03-18 09:59 UTC, elena-lyulina commented on src/main/kotlin/homework1/task_3.kt
> +const val FILE_NAME = "ActionList.json"
кладем
файлы
в ресурсы
!!!

(Я вам на лекции это рассказывала, Настя тебе в комментах это уже написала, ну что ж такое-то!)

2021-03-18 09:59 UTC, elena-lyulina commented on src/main/kotlin/homework1/task_3.kt
> +    Move(NUMBER0, NUMBER3).doAction(storage)
Тут странно получается, у тебя Number0 играет одновременно и роль числа 3 (когда ты кладешь его в начало списка), и индекса 3 (когда ты выполняешь Move). Так не должно быть, у каждой переменной должна быть одна функция, и если у двух переменных совпадает значение (3), но не функции, то не надо их объединять в одну переменную, это очень сильно может запутать

2021-03-18 09:59 UTC, elena-lyulina commented on src/main/kotlin/homework1/task_3.kt
>  const val NUMBER5 = 5
Немного про константы:
Не стоит делать глобальные константы, если они используются только в одном месте в одном файлы. Они были придуманы не для этого, а для реально глобальных констант, которые везде используются, например, ты хочешь чисто пи записать куда-то и везде использовать. Если же они используются только в одном месте, то и делать надо так, чтобы их было видно только в одном месте -- не надо их всем показывать (вспоминаем инкапсуляцию)

Да, я знаю, что detekt ругается, если их делать не константами. В общем случае действительно не должно быть магических чисел в коде, это [плохой](https://refactoring.guru/replace-magic-number-with-symbolic-constant) паттерн программирования. Но давай поймем, что у тебя сейчас немного другой случай -- ты используешь эти числа для своеобразного **тестирования**, того, что обычно не выносится в src main, а лежит в совсем другой папке и соответственно там немного другие правила. Тесты вы скоро начнете добавлять, и проблем с magic number у вас уже не будет, так как вы просто перестанете писать такой код в main. А пока предлагаю поставить на этот файл `@file:Suppress("MagicNumber")`, чтобы детект не ругался, с полным осознанием почему мы сейчас так можем сделать и почему только на этом файле (если оно к тебе еще не пришло, скажи, пожалуйста, постараюсь подробнее объяснить)

Вместо глобальных констант таких, давай сделаем внутри `fun main()` переменную `numbers` с массивом из чисел, чтобы ты потом мог к ним по индексам обращаться, и отдельно переменные для индексов для move action (я в соседнем комменте написала, почему так надо сделать)

2021-03-18 12:19 UTC, elena-lyulina requested changes
ты не поправил один комментарий про то, что вообще-то не очень иметь переменные с двумя функциями и использовать их то как числа, то как индексы

создай, пожалуйста, отдельные переменные для индексов

2021-03-18 21:12 UTC, elena-lyulina approved these changes
Ура!

2021-03-18 21:12 UTC, merged